name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Push to Personal Repository
        run: |
          git config user.email "cjustinobi@gmail.com"
          git config user.name "cjustinobi"
          git remote add justin https://github.com/cjustinobi/treeviah-frontend.git
          git push justin main
        # env:
        #   PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
